import manifest from '__STATIC_CONTENT_MANIFEST';
import * as build from '../build/index.js';
import { createFetchHandler } from './adapter';

const handleFetch = createFetchHandler({
  /**
   * Remix build
   */
  build,

  /**
   * Assets manifest of the public directory
   * Auotmatically generated by Wrangler
   */
  manifest,

  /**
   * Context to be available on `loader` or `action`, default to `undefined` if not defined
   * @param request Request object
   * @param env Variables defined on the environment
   * @param ctx Exectuion context, i.e. ctx.waitUntil() or ctx.passThroughOnException();
   * @returns Context
   */
  getLoadContext(request, env, ctx) {
    return { env, ctx };
  },

  /**
   * Setup CDN Cache for the remix response
   * No cache will be set if the function is not defined
   * or if the function returns undefined or null
   * @returns Cache
   */
  getCache() {
    return caches.open(process.env.VERSION);
  },
});

const worker: ExportedHandler = {
  fetch: handleFetch,
};

export default worker;
